# For more information: https://laravel.com/docs/sail
version: '3'
services:
    laravel.test:
        build:
            context: ./vendor/laravel/sail/runtimes/8.1
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: sail-8.1/app
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '${APP_PORT:-9192}:80'
            - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
        volumes:
            - '.:/var/www/html'
        networks:
            - sail
        depends_on:
            - pgsql
#            - redis
#            - meilisearch
#            - mailhog
#            - selenium
    pgsql:
        image: 'postgres:13'
        ports:
            - '${FORWARD_DB_PORT:-5432}:5432'
        environment:
            PGPASSWORD: '${DB_PASSWORD:-secret}'
            POSTGRES_DB: '${DB_DATABASE}'
            POSTGRES_USER: '${DB_USERNAME}'
            POSTGRES_PASSWORD: '${DB_PASSWORD:-secret}'
        volumes:
            - 'sailpgsql:/var/lib/postgresql/data'
        networks:
            - sail
        healthcheck:
            test: [ "CMD", "pg_isready", "-q", "-d", "${DB_DATABASE}", "-U", "${DB_USERNAME}" ]
            retries: 3
            timeout: 5s
#    mailhog:
#        image: 'mailhog/mailhog:latest'
#        ports:
#            - '${FORWARD_MAILHOG_PORT:-1025}:1025'
#            - '${FORWARD_MAILHOG_DASHBOARD_PORT:-8025}:8025'
#        networks:
#            - sail
    #    phpmyadmin:
    #        image: phpmyadmin/phpmyadmin
    #        links:
    #            - mysql:mysql
    #        ports:
    #            - 8080:80
    #        environment:
    #            MYSQL_USERNAME: "${DB_USERNAME}"
    #            MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
    #            PMA_HOST: mysql
    #        networks:
    #            - sail
#    selenium:
#        image: 'selenium/standalone-chrome'
#        volumes:
#            - '/dev/shm:/dev/shm'
#        networks:
#            - sail
networks:
    sail:
        driver: bridge
volumes:
    sailpgsql:
        driver: local
